#!/usr/bin/env python3
# Author: Suraj Ravichandran
# 05/29/2024
import uuid
from pydantic import BaseModel, Field, ConfigDict


class UserInput(BaseModel):
    id: uuid.UUID = Field(default_factory=uuid.uuid4, alias="_id", description="User ID which is generated by the system")
    first_name: str = Field(..., description="First name of the User")
    last_name: str = Field(..., description="Last name of the User")
    username: str = Field(..., description="Username (unique)")
    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "first_name": "Suraj",
                "last_name": "Ravichandran",
                "username": "surajravi"
            }
        }
    )


class User(UserInput):

    model_config = ConfigDict(
        populate_by_name=True,
        json_schema_extra={
            "example": {
                "id": "6d9e588d-424a-4af5-a5e7-f34ba7f75006",
                "first_name": "Suraj",
                "last_name": "Ravichandran",
                "username": "surajravi"
            }
        }
    )


class UserCollection(BaseModel):
    """
    A container holding a list of `User` instances.

    This exists because providing a top-level array in a JSON response can be a [vulnerability](https://haacked.com/archive/2009/06/25/json-hijacking.aspx/)

    (see https://www.mongodb.com/developer/languages/python/python-quickstart-fastapi/)
    """
    users: list[User]
    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "users": [
                    {
                        "id": "97c2e676-b271-4cde-9f54-1fe1f9a1a037",
                        "first_name": "Jim",
                        "last_name": "Jones",
                        "username": "jjones"
                    },
                    {
                        "id": "4efdddd4-2524-462e-8d91-762fc9ed7395",
                        "first_name": "Winston",
                        "last_name": "Rogers",
                        "username": "winst_rogers"
                    },
                    {
                        "id": "d8cb4a53-f61b-48f0-8106-5676b6e83684",
                        "first_name": "Diane",
                        "last_name": "Simmons",
                        "username": "dianesim"
                    }
                ]
            }
        }
    )
